// Generated by jextract

package demo.ffi;

import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static java.lang.foreign.ValueLayout.OfLong;

final class Constants$root {

    // Suppresses default constructor, ensuring non-instantiability.
    private Constants$root() {
    }

    static final OfLong C_LONG_LONG$LAYOUT = JAVA_LONG;
}


