// Generated by jextract

package demo.ffi;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {
    }

    static final MethodHandle compute_sum$MH = RuntimeHelper.downcallHandle(
            "compute_sum",
            FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
                    Constants$root.C_LONG_LONG$LAYOUT,
                    Constants$root.C_LONG_LONG$LAYOUT
            )
    );
    static final MethodHandle hello_world$MH = RuntimeHelper.downcallHandle(
            "hello_world",
            FunctionDescriptor.ofVoid()
    );
}


