// Generated by jextract

package demo.ffi;

import java.lang.foreign.FunctionDescriptor;

import static java.lang.foreign.ValueLayout.JAVA_LONG;

public class lib_h {

    /**
     * {@snippet :
     * void hello_world();
     *}
     */
    public static void hello_world() {
        var void__ = FunctionDescriptor.ofVoid();
        var mh = RuntimeHelper.requireNonNull(RuntimeHelper.downcallHandle("hello_world", void__), "hello_world");
        try {
            mh.invokeExact();
        } catch (Throwable ex) {
            throw new AssertionError("should not reach here", ex);
        }
    }



    //    /**
//     * {@snippet :
//     * uintptr_t compute_sum(uintptr_t left, uintptr_t right);
//     *}
//     */
//    public static long compute_sum(long left, long right) {
//        var long__long_long = FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG);
//        var mh = RuntimeHelper.requireNonNull(RuntimeHelper.downcallHandle("compute_sum", long__long_long), "compute_sum");
//        try {
//            return (long) mh.invokeExact(left, right);
//        } catch (Throwable ex) {
//            throw new AssertionError("should not reach here", ex);
//        }
//    }

}


