// Generated by jextract

package demo.ffi;

public class lib_h {

    /**
     * {@snippet :
     * uintptr_t compute_sum(uintptr_t left, uintptr_t right);
     *}
     */
    public static long compute_sum(long left, long right) {
        var mh$ = RuntimeHelper.requireNonNull(constants$0.compute_sum$MH, "compute_sum");
        try {
            return (long) mh$.invokeExact(left, right);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * {@snippet :
     * void hello_world();
     *}
     */
    public static void hello_world() {
        var mh$ = RuntimeHelper.requireNonNull(constants$0.hello_world$MH, "hello_world");
        try {
            mh$.invokeExact();
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}


